#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-sisu
Version  : 1.1
Release  : 5
URL      : https://repo1.maven.org/maven2/org/sonatype/sisu/sisu-charger/1.1/sisu-charger-1.1.jar
Source0  : https://repo1.maven.org/maven2/org/sonatype/sisu/sisu-charger/1.1/sisu-charger-1.1.jar
Source1  : https://repo1.maven.org/maven2/org/eclipse/sisu/sisu-inject/0.3.2/sisu-inject-0.3.2.pom
Source2  : https://repo1.maven.org/maven2/org/sonatype/sisu/inject/guice-plexus/1.4.2/guice-plexus-1.4.2.pom
Source3  : https://repo1.maven.org/maven2/org/sonatype/sisu/sisu-charger/1.1/sisu-charger-1.1.pom
Source4  : https://repo1.maven.org/maven2/org/sonatype/sisu/sisu-guava/0.9.9/sisu-guava-0.9.9.jar
Source5  : https://repo1.maven.org/maven2/org/sonatype/sisu/sisu-guava/0.9.9/sisu-guava-0.9.9.pom
Source6  : https://repo1.maven.org/maven2/org/sonatype/sisu/sisu-inject-bean/1.4.2/sisu-inject-bean-1.4.2.jar
Source7  : https://repo1.maven.org/maven2/org/sonatype/sisu/sisu-inject-bean/1.4.2/sisu-inject-bean-1.4.2.pom
Source8  : https://repo1.maven.org/maven2/org/sonatype/sisu/sisu-inject-plexus/1.4.2/sisu-inject-plexus-1.4.2.jar
Source9  : https://repo1.maven.org/maven2/org/sonatype/sisu/sisu-inject-plexus/1.4.2/sisu-inject-plexus-1.4.2.pom
Source10  : https://repo1.maven.org/maven2/org/sonatype/sisu/sisu-inject/1.4.2/sisu-inject-1.4.2.pom
Source11  : https://repo1.maven.org/maven2/org/sonatype/sisu/sisu-inject/2.3.0/sisu-inject-2.3.0.pom
Source12  : https://repo1.maven.org/maven2/org/sonatype/sisu/sisu-parent/1.4.2/sisu-parent-1.4.2.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: mvn-sisu-data = %{version}-%{release}

%description
No detailed description available

%package data
Summary: data components for the mvn-sisu package.
Group: Data

%description data
data components for the mvn-sisu package.


%prep

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/sonatype/sisu/sisu-charger/1.1
cp %{SOURCE0} %{buildroot}/usr/share/java/.m2/repository/org/sonatype/sisu/sisu-charger/1.1/sisu-charger-1.1.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/eclipse/sisu/sisu-inject/0.3.2
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/org/eclipse/sisu/sisu-inject/0.3.2/sisu-inject-0.3.2.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/sonatype/sisu/inject/guice-plexus/1.4.2
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/org/sonatype/sisu/inject/guice-plexus/1.4.2/guice-plexus-1.4.2.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/sonatype/sisu/sisu-charger/1.1
cp %{SOURCE3} %{buildroot}/usr/share/java/.m2/repository/org/sonatype/sisu/sisu-charger/1.1/sisu-charger-1.1.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/sonatype/sisu/sisu-guava/0.9.9
cp %{SOURCE4} %{buildroot}/usr/share/java/.m2/repository/org/sonatype/sisu/sisu-guava/0.9.9/sisu-guava-0.9.9.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/sonatype/sisu/sisu-guava/0.9.9
cp %{SOURCE5} %{buildroot}/usr/share/java/.m2/repository/org/sonatype/sisu/sisu-guava/0.9.9/sisu-guava-0.9.9.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/sonatype/sisu/sisu-inject-bean/1.4.2
cp %{SOURCE6} %{buildroot}/usr/share/java/.m2/repository/org/sonatype/sisu/sisu-inject-bean/1.4.2/sisu-inject-bean-1.4.2.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/sonatype/sisu/sisu-inject-bean/1.4.2
cp %{SOURCE7} %{buildroot}/usr/share/java/.m2/repository/org/sonatype/sisu/sisu-inject-bean/1.4.2/sisu-inject-bean-1.4.2.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/sonatype/sisu/sisu-inject-plexus/1.4.2
cp %{SOURCE8} %{buildroot}/usr/share/java/.m2/repository/org/sonatype/sisu/sisu-inject-plexus/1.4.2/sisu-inject-plexus-1.4.2.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/sonatype/sisu/sisu-inject-plexus/1.4.2
cp %{SOURCE9} %{buildroot}/usr/share/java/.m2/repository/org/sonatype/sisu/sisu-inject-plexus/1.4.2/sisu-inject-plexus-1.4.2.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/sonatype/sisu/sisu-inject/1.4.2
cp %{SOURCE10} %{buildroot}/usr/share/java/.m2/repository/org/sonatype/sisu/sisu-inject/1.4.2/sisu-inject-1.4.2.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/sonatype/sisu/sisu-inject/2.3.0
cp %{SOURCE11} %{buildroot}/usr/share/java/.m2/repository/org/sonatype/sisu/sisu-inject/2.3.0/sisu-inject-2.3.0.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/sonatype/sisu/sisu-parent/1.4.2
cp %{SOURCE12} %{buildroot}/usr/share/java/.m2/repository/org/sonatype/sisu/sisu-parent/1.4.2/sisu-parent-1.4.2.pom


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/org/eclipse/sisu/sisu-inject/0.3.2/sisu-inject-0.3.2.pom
/usr/share/java/.m2/repository/org/sonatype/sisu/inject/guice-plexus/1.4.2/guice-plexus-1.4.2.pom
/usr/share/java/.m2/repository/org/sonatype/sisu/sisu-charger/1.1/sisu-charger-1.1.jar
/usr/share/java/.m2/repository/org/sonatype/sisu/sisu-charger/1.1/sisu-charger-1.1.pom
/usr/share/java/.m2/repository/org/sonatype/sisu/sisu-guava/0.9.9/sisu-guava-0.9.9.jar
/usr/share/java/.m2/repository/org/sonatype/sisu/sisu-guava/0.9.9/sisu-guava-0.9.9.pom
/usr/share/java/.m2/repository/org/sonatype/sisu/sisu-inject-bean/1.4.2/sisu-inject-bean-1.4.2.jar
/usr/share/java/.m2/repository/org/sonatype/sisu/sisu-inject-bean/1.4.2/sisu-inject-bean-1.4.2.pom
/usr/share/java/.m2/repository/org/sonatype/sisu/sisu-inject-plexus/1.4.2/sisu-inject-plexus-1.4.2.jar
/usr/share/java/.m2/repository/org/sonatype/sisu/sisu-inject-plexus/1.4.2/sisu-inject-plexus-1.4.2.pom
/usr/share/java/.m2/repository/org/sonatype/sisu/sisu-inject/1.4.2/sisu-inject-1.4.2.pom
/usr/share/java/.m2/repository/org/sonatype/sisu/sisu-inject/2.3.0/sisu-inject-2.3.0.pom
/usr/share/java/.m2/repository/org/sonatype/sisu/sisu-parent/1.4.2/sisu-parent-1.4.2.pom
